Handled tls authentication errors
vostok/clusterclient.transport pull request #17
Opened 2022-08-09 06:38 UTC by HolyPrapor

2022-08-23 11:12 UTC, TGladysheva requested changes

2022-08-23 11:12 UTC, TGladysheva commented on Vostok.ClusterClient.Transport/Native/ErrorHandler.cs
> +                            LogConnectionFailure(request, authenticationException);
А может тут залогировать более конкретную ошибку? с упоминанием, что это ошибка аутентификации. А то сейчас мы уже привыкли, что Connection failure - это выключенная реплика. При невнимательном чтении логов можно и неправильно интерпретировать

2022-08-23 11:12 UTC, TGladysheva commented on Vostok.ClusterClient.Transport/Sockets/ErrorHandler.cs
> +                    return (Responses.BadRequest, authException);
Возвращаемые статусы на каждую ошибку фиксируются в ErrorHandler_Tests. Давай эту тоже добавим туда

2022-08-23 11:12 UTC, TGladysheva commented on Vostok.ClusterClient.Transport/Native/ErrorHandler.cs
> +                            return Responses.BadRequest;
А еще, если я правильно поняла, то в webrequest возвращается статус ResponseCode.ConnectFailure на такую ошибку. 400 ведь можно спутать с ответом самого сервера? Как думаешь? Может на ConnectFailure  заменим?

2022-08-26 02:19 UTC, HolyPrapor commented on Vostok.ClusterClient.Transport/Native/ErrorHandler.cs
> +                            return Responses.BadRequest;
По-дефолту ClusterClient мне возвращает 453 (вроде это случалось с любым транспортом).

В целом, можно и `ConnectFailure`, у меня тут нет какого-то особенного мнения. 
Единственное, что смущает - обычно такая ошибка у меня с сетевыми проблемами ассоциируется.

И если где-то ставить `ConnectFailure`, то лучше во всех транспортах, наверное?

2022-08-26 05:21 UTC, TGladysheva commented on Vostok.ClusterClient.Transport/Native/ErrorHandler.cs
> +                            return Responses.BadRequest;
Да, лучше во всех одинаковую ошибку, конечно. Я просто только в одном месте написала комментарий.
450 или 453 - не принципиально, мне кажется. Только не 400

2022-08-26 05:28 UTC, HolyPrapor commented on Vostok.ClusterClient.Transport/Native/ErrorHandler.cs
> +                            return Responses.BadRequest;
Ок, пусть будет 450

2022-09-05 12:52 UTC, merged